<?php
return array (
  'index.html' => '首页',
  'activity' => '活动',
  'article' => '文章',
  'comment' => '评论',
  'digg' => 'Digg',
  'favorite' => '收藏',
  'guestbook' => '留言本',
  'history' => '历史页面',
  'interview' => '访谈',
  'link' => '链接',
  'magazine' => '杂志',
  'member' => '会员',
  'mood' => '心情',
  'page' => '页面',
  'paper' => '报纸',
  'picture' => '组图',
  'rss' => 'RSS',
  'search' => '搜索',
  'space' => '专栏',
  'special' => '专题',
  'survey' => '调查',
  'system' => '系统',
  'video' => '视频',
  'vote' => '投票',
  'wap' => 'WAP',
);