<?php
return array (
  393743 => 
  array (
    'id' => '393743',
    'catid' => '349',
    'typeid' => '0',
    'title' => '古典美女',
    'style' => '',
    'thumb' => 'http://pnews.ck.huoshow.com/uploadfile/2013/0115/20130115041315573.jpg',
    'keywords' => '美女',
    'description' => '',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=350&id=301733',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1358237503',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393743',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393753 => 
  array (
    'id' => '393753',
    'catid' => '349',
    'typeid' => '0',
    'title' => '蓝贴：Beta平衡性补丁11',
    'style' => '',
    'thumb' => 'http://pnews.ck.huoshow.com/uploadfile/2013/0111/20130111102210267.jpg',
    'keywords' => '',
    'description' => '以下内容由网易星际专区 超昂草莓 整理编译，转载请注明出处！今天，官方发布了《虫群之心》Beta第11号补丁，其中主要对人族的许多单位进...',
    'posids' => '1',
    'url' => 'http://pnews.ck.huoshow.com/index.php?m=content&c=index&a=show&catid=333&id=301611',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357871494',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393753',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393752 => 
  array (
    'id' => '393752',
    'catid' => '349',
    'typeid' => '0',
    'title' => '毁灭术也有了圣疗？5.2大雕文灰烬转换评测',
    'style' => '',
    'thumb' => 'http://pnews.ck.huoshow.com/uploadfile/2013/0110/20130110054816783.jpg',
    'keywords' => '',
    'description' => '在MOP里，术士可谓是成为了暴雪的宠儿，PVP和PVE两丰收。在5.2里，暴雪又给毁灭术新增了一个大雕纹--灰烬转换雕文，提高灰烬转换50%治疗量...',
    'posids' => '1',
    'url' => 'http://pnews.ck.huoshow.com/index.php?m=content&c=index&a=show&catid=333&id=301610',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357871266',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393752',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393751 => 
  array (
    'id' => '393751',
    'catid' => '349',
    'typeid' => '0',
    'title' => '蓝雪、红梅、忆江南、醉荷',
    'style' => '',
    'thumb' => 'http://pnews.ck.huoshow.com/uploadfile/2013/0115/20130115041615913.jpg',
    'keywords' => '醉荷',
    'description' => '',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=349&id=301734',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1358237749',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393751',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393750 => 
  array (
    'id' => '393750',
    'catid' => '349',
    'typeid' => '0',
    'title' => '安卓游戏角色扮演测试②',
    'style' => '',
    'thumb' => 'http://pnews.trunk.huoshow.com/uploadfile/2013/0121/20130121035324677.jpg',
    'keywords' => '角色扮演',
    'description' => '做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做球宝贝做...',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=349&id=301661',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357960367',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393750',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393749 => 
  array (
    'id' => '393749',
    'catid' => '349',
    'typeid' => '0',
    'title' => '安卓游戏角色扮演测试①',
    'style' => '',
    'thumb' => 'http://pnews.trunk.huoshow.com/uploadfile/2013/0121/20130121035127725.jpg',
    'keywords' => '角色扮演',
    'description' => '加快了经济就斤斤计较斤斤计较斤斤计较斤斤计较斤斤计较斤斤计较回家撒反复反复反复反反复反复反复反复反复反复反复反复反复反复反复反复反...',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=349&id=301660',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357960228',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393749',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393748 => 
  array (
    'id' => '393748',
    'catid' => '349',
    'typeid' => '0',
    'title' => '传索尼或出售其东京办公大楼 售价约1000亿日元',
    'style' => '',
    'thumb' => 'http://pnews.ck.huoshow.com/uploadfile/2013/0111/20130111110146849.jpg',
    'keywords' => '日元',
    'description' => '1月11日消息，据国外媒体报道，知情人士透露，索尼正在考虑出售它在东京的Sony City Osaki办公大楼，它估计的售价在1000亿日元（约合11亿...',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=349&id=301619',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357873185',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393748',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393747 => 
  array (
    'id' => '393747',
    'catid' => '349',
    'typeid' => '0',
    'title' => '手机游戏测试测试②',
    'style' => '',
    'thumb' => 'http://www.huoshow.com/upload/2011/1122/thumb_941_627_1321933394248.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=348&id=301659',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357960179',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393747',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393746 => 
  array (
    'id' => '393746',
    'catid' => '349',
    'typeid' => '0',
    'title' => '安卓游戏益智休闲测试①',
    'style' => '',
    'thumb' => 'http://pnews.trunk.huoshow.com/uploadfile/2013/0121/20130121035403246.jpg',
    'keywords' => '益智',
    'description' => '进口国家的房价的快感骄傲健康的价格可怜的价格卡拉的价格就打开工具打开更加快了地方价格加快了大家公开的价格看了据德国进口德国进口数量...',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=348&id=301657',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357959511',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393746',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  393745 => 
  array (
    'id' => '393745',
    'catid' => '349',
    'typeid' => '0',
    'title' => '安卓游戏策略经营①',
    'style' => '',
    'thumb' => 'http://pnews.trunk.huoshow.com/uploadfile/2013/0121/20130121040800995.jpg',
    'keywords' => '游戏策略',
    'description' => '价格卡的说价格可垃圾的思考两个就挨打开了个骄傲的高发计算机公开量大价格拉到就两个价格卡的说价格可垃圾的思考两个就挨打开了个骄傲的高...',
    'posids' => '1',
    'url' => 'http://pnews.trunk.huoshow.com/index.php?m=content&c=index&a=show&catid=350&id=301662',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1357960515',
    'updatetime' => '1358757208',
    'gamesize' => '',
    'developers' => '',
    'gametype' => '',
    'releasedate' => '',
    'chargingmode' => '',
    'price' => '',
    'stars' => '',
    'hitsid' => 'c-18-393745',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>