var relateddata;
function related_select(a){var b=related_data();window.relateddata=b[0];window.relatedids=b[1];a=showModalDialog("?app=system&controller=related&action=search&keywords="+encodeURIComponent(a),window,"dialogWidth:820px;dialogHeight:465px;help:0;status:0;center:yes;scroll:no");if(a!=null){b="";for(var d=0;d<a.length;d++){if(a[d][0])a[d][0]=a[d][0].substr(0,14);b+='<li><input type="hidden" name="related[]" id="related_'+d+'" value="'+a[d].join("|")+'"/><a href="'+a[d][2]+'" target="_blank">'+a[d][0]+
"</a></li>\n"}$("#related_data").html(b)}}function related_data(){var a=[],b=[];$("#related_data input").each(function(d){a[d]=$(this).val();b[d]=parseInt($(this).val().split("|").pop())});return[a,b]}
function related_append(a){var b="";$.each(a,function(d,c){if(c.title)c.title=c.title.substr(0,20);var e=window.dialogArguments.relatedids.indexOf(parseInt(c.contentid))!=-1?'checked="checked"':"";rid++;b+='<li id="'+c.contentid+'">';b+=' <input type="checkbox" name="related" id="related_'+c.contentid+'" value="'+c.title+"|"+c.thumb+"|"+c.url+"|"+c.time+"|"+c.contentid+'" class="checkbox_style" '+e+'" onclick="related_checked('+c.contentid+')"/>';b+='   <a href="'+c.caturl+'" target="_blank">'+c.catname+
'</a>\uff1a<a href="'+c.url+'" target="_blank">'+c.title+"</a>";b+='   <span class="date">'+c.time+"</span>";b+="</li>"});$("#data").append(b);init_panel()}
function related_picture(a){var b="";$.each(a,function(d,c){rid++;b+='<li id="'+rid+'">';b+=' <input type="radio" name="related_picture" id="related_'+rid+'" value="'+c.contentid+'" class="checkbox_style" />';b+='   <a href="'+c.caturl+'">'+c.catname+'</a>\uff1a<a href="'+c.url+'" target="_blank">'+c.title+"</a>";b+='   <span class="date">'+c.time+"</span>";b+="</li>"});$("#data").append(b)}
function related_picture_ok(a){if(a.state){$("#data").empty();sort_mode="";related_picture(a.data);count=a.data.length;total=a.total;$("#count").html(a.data.length);$("#total").html(a.total)}else alert(a.error)}function picture_ok(){var a="";$("input[name*='related_picture']").each(function(){if($(this).attr("checked")==true)a=$(this).val()});window.returnValue=a;window.close()}
function related_checked(a){if($("#related_"+a).attr("checked")==true)related_list_add(a,$("#related_"+a).val());else{$("#checked_"+a).parent().remove();checked_count--;$("#checked_count").html(checked_count)}init_panel()}function init_panel(){$("#list").find("img").show().css("visibility","visible");if($("#list").children().length==1)$("#list").find("img:lt(2)").hide();else{$("#list li:first").find("img:eq(0)").hide();$("#list li:last").find("img:eq(1)").css("visibility","hidden")}}
function related_checked_delete(a){$("#related_"+a).attr("checked",false);$("#checked_"+a).parent().remove();checked_count--;init_panel();$("#checked_count").html(checked_count)}function related_checked_up(a){a=$("#checked_"+a).parent();if(a.prev().is("li")){var b=a.prev().html(),d=a.html();a.prev().html(d);a.html(b)}init_panel()}function related_checked_down(a){a=$("#checked_"+a).parent();if(a.next().is("li")){var b=a.next().html(),d=a.html();a.next().html(d);a.html(b)}init_panel()}
function related_search_ok(a){if(a.state){$("#data").empty();sort_mode="";related_append(a.data);count=a.data.length;total=a.total;$("#count").html(a.data.length);$("#total").html(a.total)}else alert(a.error)}function init(){checked_count++}
function related_list_add(a,b){checked_count++;var d=b.split("|");a=a?a:d[4];var c="";c+='<li class="layout">';c+='   <span id="checked_'+a+'" class="f_r"><img src="images/up.gif" alt="\u5411\u4e0a" title="\u5411\u4e0a" height="16" width="16" class="hand" onclick="related_checked_up('+a+')"/> <img src="images/down.gif" alt="\u5411\u4e0b" title="\u5411\u4e0b" height="16" width="16" class="hand" onclick="related_checked_down('+a+')"/> <img src="images/edit.gif" alt="\u7f16\u8f91" title="\u7f16\u8f91" height="16" width="16" class="hand" onclick="related_edit('+
a+')"/> <img src="images/del.gif" alt="\u53d6\u6d88" title="\u53d6\u6d88" height="16" width="16" class="hand" onclick="related_checked_delete('+a+')"/></span>';c+='   <span class="f_l"><input type="hidden" name="data_'+a+'" id="data_'+a+'" value="'+b+'" /><a id="a_'+a+'" href="'+d[2]+'" target="_blank">'+d[0]+"</a></span>";c+="</li>";$("#list").append(c);$("#checked_count").html(checked_count)}
function related_list_edit(a,b){var d=b.split("|");$("#data_"+a).val(b);$("#a_"+a).html(d[0]);$("#a_"+a).attr("href",d[2])}function related_add(){ct.form("\u6dfb\u52a0\u76f8\u5173","?app=system&controller=related&action=add",400,200,function(){var a=$("#title").val()+"|"+$("#thumb").val()+"|"+$("#url").val()+"|"+$("#time").val();rid++;related_list_add(rid,a);init_panel();return true})}
function related_edit(a){ct.form("\u4fee\u6539\u76f8\u5173","?app=system&controller=related&action=edit&rid="+a,400,200,function(){var b=$("#edit_title").val()+"|"+$("#edit_thumb").val()+"|"+$("#edit_url").val()+"|"+$("#edit_time").val();related_list_edit($("#edit_rid").val(),b);return true})}var sort_mode="";
function related_sort(a){sort_mode=a;var b=[];$("#data > li").each(function(c){b[c]=[$(this).attr("id"),$(this).html(),$(this).children(".date").html(),$("#related_"+$(this).attr("id")).attr("checked")]});b.sort(function(c,e){return sort_mode=="asc"?c[2].localeCompare(e[2]):e[2].localeCompare(c[2])});var d="";$.each(b,function(c,e){d+='<li id="'+e[0]+'">'+e[1]+"</li>\n"});$("#data").html(d);$.each(b,function(c,e){e[3]==true&&$("#related_"+e[0]).attr("checked",true)})}
function related_ok(){var a=[];$("input[name*='data']").each(function(b){a[b]=$(this).val().split("|")});window.returnValue=a;window.close()}function related_cancel(){window.returnValue=null;window.close()}function async_form(a,b){$("#"+a).bind("submit.form-plugin",function(){$(this).ajaxSubmit({dataType:"json",success:function(d){if(d.state)if(d.redirect)window.location.href=d.redirect=="refresh"?window.location.href:d.redirect;b&&eval("("+b+")")(d)}});return false})};
